apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns
  labels:
    app: cloudflare-ddns
spec:
  # Run every 5 minutes
  # Format: "minute hour day month weekday"
  # Examples:
  #   "*/5 * * * *"     - Every 5 minutes
  #   "*/15 * * * *"    - Every 15 minutes
  #   "0 */1 * * *"     - Every hour
  #   "0 */6 * * *"     - Every 6 hours
  schedule: "*/5 * * * *"

  # Keep last 3 successful and 1 failed job for debugging
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cloudflare-ddns
        spec:
          # Use host network to detect actual public IP
          # Required for IPv6 support
          hostNetwork: true

          restartPolicy: OnFailure

          # Security context for the pod
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000

          containers:
          - name: cloudflare-ddns
            image: timothyjmiller/cloudflare-ddns:latest

            # Security context for the container
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1000
              capabilities:
                drop:
                  - ALL

            # Environment variables from ConfigMap and Secret
            envFrom:
            - configMapRef:
                name: cloudflare-ddns-config
            - secretRef:
                name: cloudflare-ddns-secret

            # Optional: Additional environment variables
            env:
            - name: UPDATE_CRON
              value: "@once"  # Run once per job (don't use internal cron)

            # Resource limits (adjust based on your needs)
            resources:
              requests:
                memory: "32Mi"
                cpu: "10m"
              limits:
                memory: "64Mi"
                cpu: "100m"
